[package]
name = "modelica-gpui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
modelica-core = { path = "../modelica-core" }
modelica-render = { path = "../modelica-render" }
gpui = { git = "https://github.com/zed-industries/zed", rev = "12ef40c31659ddb879bdb39481b7fc9524ac8ffa" }

[target.'cfg(target_os = "windows")'.dependencies]
gpui_platform = { git = "https://github.com/zed-industries/zed", package = "gpui_platform", rev = "12ef40c31659ddb879bdb39481b7fc9524ac8ffa" }

[target.'cfg(target_os = "linux")'.dependencies]
gpui_platform = { git = "https://github.com/zed-industries/zed", package = "gpui_platform", rev = "12ef40c31659ddb879bdb39481b7fc9524ac8ffa", features = ["wayland", "x11"] }
